wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.18.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1732946493
    t:
      1:
      - 1
      - 41
      - 43
      - 55
      3:
      - 4
      - 23
      - 34
      - 35
      - 42
      - 55
      4: 3.10.12
      5: 0.18.7
      8:
      - 5
      13: linux-x86_64
